@startuml
skinparam SequenceMessageAlignment center

title Sign-in with Google Design (Auto code with PKCE flow)
"Mobile App Browser" -> "Mobile App Browser" : A.1 handler for Login with Google Button 
note left
create random(v)
$ = sha256(v)
end note

"Mobile App Browser" -> "Google Auth Service": A.2 ...to Google Login with $
activate "Google Auth Service"
note right: store $
"Mobile App Browser" <- "Google Auth Service": A.3 returns login page

activate "Mobile App Browser"
"Mobile App Browser" -> "Google Auth Service": A.4 submits credentials
deactivate "Mobile App Browser"
"Mobile App Browser" <- "Google Auth Service" : A.5 deep link to App with auth_code
deactivate "Google Auth Service"
|||
|||
"Mobile App Browser" -> "Flask Auth Service" : B.1 request token with (auth_code, v)
"Flask Auth Service" -> "Google Auth Service": B.2 exchange auth_code for (openid, refresh_token)
note left
    validate 
    - client id
    - client secret: $ = sha256(v)
    - auth_code
end note
"Google Auth Service" -> "Flask Auth Service": B.3 return (openid, refresh_token)
note right
    openid, refresh_token
    register session_id
end note
"Flask Auth Service" -> "Mobile App Browser": session_id, close browser(via Deeplink handler)

@enduml